name: Docker Image CI

on:
  push:
    branches: [ "dev/back" ]
  pull_request:
    branches: [ "dev/back" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flower-map-server:$(date +%s)
